<?php
/**
 * Contao
 * German translation file
 *
 * copyright  	Tim Gatzky 2013
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		OnePageWebsite
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['MOD']['OnePageWebsite'] = array('One-Page-Website', 'Erstellt One-Page-Webseiten über die Seitenstruktur.');

/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['onepagewebsite'] 			= 'One-Page-Website';
$GLOBALS['TL_LANG']['FMD']['onepagewebsiteregular']		= array('One-Page-Website: Normale Struktur', 'Erstellt die Seiten aus einer Referenzseite.');
$GLOBALS['TL_LANG']['FMD']['onepagewebsitecustom']		= array('One-Page-Website: Individuelle Struktur', 'Wählen Sie die Seiten, die dargestellt werden sollen.');
$GLOBALS['TL_LANG']['FMD']['onepagewebsitenavigation']	= array('One-Page-Website: Navigationsmenü', 'Erstellt ein Navigationsmenü aus Seiten.');

?>