<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  	Tim Gatzky 2013 
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		OnePageWebsite
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_page']['opw_hide'] = array('Hide in OnePageWebsite', 'Ignore this page in a one-page website structure.');

?>