<?php
/**
 * Contao
 * English translation file
 *
 * copyright  	Tim Gatzky 2013
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		OnePageWebsite
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['MOD']['OnePageWebsite'] 			= array('One-Page-Website', 'Create a one-page website using the page structure');

/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['onepagewebsite'] 			= 'One-Page-Website';
$GLOBALS['TL_LANG']['FMD']['onepagewebsiteregular']		= array('One-Page-Website: Regular structure', 'Create the pages via reference page');
$GLOBALS['TL_LANG']['FMD']['onepagewebsitecustom']		= array('One-Page-Website: Individual structure', 'Custom page selection');
$GLOBALS['TL_LANG']['FMD']['onepagewebsitenavigation']	= array('One-Page-Website: Navigation menu', 'Creates a navigation menu for the pages');

?>