<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  	Tim Gatzky 2013
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		OnePageWebsite
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_module']['opw_template'] 		= array('Structure template', 'Please choose the template file.');
$GLOBALS['TL_LANG']['tl_module']['opw_mod_template'] 	= array('Module template', 'Please choose the template file.');
$GLOBALS['TL_LANG']['tl_module']['rootModule'] 			= array('Reference module', 'Please choose a reference module.');


?>