<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao 
 * German translation file 
 * 
 * copyright  	Tim Gatzky 2012 
 * author     	Tim Gatzky <info@tim-gatzky.de>
 * package		OnePageWebsite
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_module']['opw_template'] = array('Struktur-Template', 'Bitte Wählen Sie ein Template aus.');
$GLOBALS['TL_LANG']['tl_module']['opw_mod_template'] = array('Modul-Template', 'Bitte Wählen Sie ein Template aus.');
$GLOBALS['TL_LANG']['tl_module']['rootModule'] = array('Referenzmodul', 'Bitte Wählen Sie das Referenzmodul aus.');


?>